/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface_restaurant;

import Inteface_employeeManagement.EmpMenu;
import Interface.Login;
import Interface_bookingManagement.RoomMenu;
import Interface_customerManagement.CusManagement;
import Java_restaurant.FOODITEMS;
import finance.mangement.Finance_Mangemant;
import interface_inventoryManagement.Inventory_Dash;
import interface_supplierManagement.Supplier_Dashboard;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maduka-PC
 */
public class ResManagement extends javax.swing.JFrame {

    FOODITEMS fooditems = new FOODITEMS();
    FOODITEMS menuitems = new FOODITEMS();
    
    public ResManagement() {
        initComponents();
    //fooditems.jcomboupdate();
    fooditems.fillFOODITEMSJTable(jTable1);
    menuitems.fillMENUITEMSJTable(jTable2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        mealspanel1 = new javax.swing.JPanel();
        jToggleButtoncus = new javax.swing.JToggleButton();
        jToggleButtonBill = new javax.swing.JToggleButton();
        jToggleButtonRest = new javax.swing.JToggleButton();
        jToggleButtonInv = new javax.swing.JToggleButton();
        jToggleButtonEmp = new javax.swing.JToggleButton();
        jToggleButtonFin = new javax.swing.JToggleButton();
        jToggleButtonSup = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4refresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        addmenu = new javax.swing.JButton();
        deletemenu = new javax.swing.JButton();
        menuitem = new javax.swing.JTextField();
        menuprice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        updatemenu = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2itemid = new javax.swing.JLabel();
        jLabel3itemname = new javax.swing.JLabel();
        jLabel4qty = new javax.swing.JLabel();
        jLabel5price = new javax.swing.JLabel();
        jTextFielditemId = new javax.swing.JTextField();
        jTextFieldqty = new javax.swing.JTextField();
        jTextFieldprice = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1additem = new javax.swing.JButton();
        jButton3deleteitem = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menuid = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("RESTAURANT MANAGEMENT");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        mealspanel1.setBackground(new java.awt.Color(0, 102, 102));

        jToggleButtoncus.setBackground(new java.awt.Color(255, 255, 204));
        jToggleButtoncus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jToggleButtoncus.setText("Customer Management");
        jToggleButtoncus.setBorder(null);
        jToggleButtoncus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtoncusActionPerformed(evt);
            }
        });

        jToggleButtonBill.setBackground(new java.awt.Color(255, 255, 204));
        jToggleButtonBill.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jToggleButtonBill.setText("Bill & Booking Management");
        jToggleButtonBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBillActionPerformed(evt);
            }
        });

        jToggleButtonRest.setBackground(new java.awt.Color(255, 255, 204));
        jToggleButtonRest.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jToggleButtonRest.setText("Restaurant Management");
        jToggleButtonRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRestActionPerformed(evt);
            }
        });

        jToggleButtonInv.setBackground(new java.awt.Color(255, 255, 204));
        jToggleButtonInv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jToggleButtonInv.setText("Inventory Management");
        jToggleButtonInv.setBorder(null);
        jToggleButtonInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonInvActionPerformed(evt);
            }
        });

        jToggleButtonEmp.setBackground(new java.awt.Color(255, 255, 204));
        jToggleButtonEmp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jToggleButtonEmp.setText("Employee Management");
        jToggleButtonEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEmpActionPerformed(evt);
            }
        });

        jToggleButtonFin.setBackground(new java.awt.Color(255, 255, 204));
        jToggleButtonFin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jToggleButtonFin.setText("Finance Management");
        jToggleButtonFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonFinActionPerformed(evt);
            }
        });

        jToggleButtonSup.setBackground(new java.awt.Color(255, 255, 204));
        jToggleButtonSup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jToggleButtonSup.setText("Supplier Management");
        jToggleButtonSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mealspanel1Layout = new javax.swing.GroupLayout(mealspanel1);
        mealspanel1.setLayout(mealspanel1Layout);
        mealspanel1Layout.setHorizontalGroup(
            mealspanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mealspanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mealspanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButtonFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtoncus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonBill, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jToggleButtonRest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mealspanel1Layout.setVerticalGroup(
            mealspanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mealspanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jToggleButtoncus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jToggleButtonBill, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButtonRest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jToggleButtonInv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jToggleButtonEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jToggleButtonFin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jToggleButtonSup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Quantity", "Price", "Total", "Bill Amount"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton4refresh.setBackground(new java.awt.Color(0, 0, 0));
        jButton4refresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4refresh.setForeground(new java.awt.Color(255, 255, 255));
        jButton4refresh.setText("REFRESH");
        jButton4refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4refreshActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(102, 102, 102));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("REFRESH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton4refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4refresh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        addmenu.setBackground(new java.awt.Color(0, 51, 204));
        addmenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addmenu.setText("ADD");
        addmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmenuActionPerformed(evt);
            }
        });

        deletemenu.setBackground(new java.awt.Color(255, 0, 0));
        deletemenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletemenu.setText("DELETE");
        deletemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletemenuActionPerformed(evt);
            }
        });

        menuitem.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemActionPerformed(evt);
            }
        });

        menuprice.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        menuprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupriceActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Item ID           :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Item Price       :");

        updatemenu.setBackground(new java.awt.Color(51, 255, 0));
        updatemenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatemenu.setText("UPDATE");
        updatemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatemenuActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("   Menu List");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2itemid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2itemid.setText("Item ID                :");

        jLabel3itemname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3itemname.setText("Item Name          :");

        jLabel4qty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4qty.setText("Quantity               :");

        jLabel5price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5price.setText("Price                     :");

        jTextFielditemId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextFieldqty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldqtyActionPerformed(evt);
            }
        });

        jTextFieldprice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldpriceActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setMaximumRowCount(30);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1additem.setBackground(new java.awt.Color(0, 51, 204));
        jButton1additem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1additem.setText("ADD");
        jButton1additem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1additemActionPerformed(evt);
            }
        });

        jButton3deleteitem.setBackground(new java.awt.Color(255, 0, 0));
        jButton3deleteitem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3deleteitem.setText("DELETE");
        jButton3deleteitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3deleteitemActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("REPORT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Order Items Details");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Item Name     :");

        menuid.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(menuitem, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(menuprice)
                            .addComponent(menuid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deletemenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updatemenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5price)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4qty)
                                        .addComponent(jLabel3itemname)
                                        .addComponent(jLabel2itemid)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFielditemId, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldqty, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldprice, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 3, Short.MAX_VALUE))
                                    .addComponent(jButton3deleteitem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1additem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111)))
                        .addGap(46, 46, 46))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addmenu)
                    .addComponent(jLabel2)
                    .addComponent(menuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updatemenu)
                        .addComponent(menuitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletemenu)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(menuprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(52, 52, 52)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2itemid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFielditemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1additem)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3itemname)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton3deleteitem)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldqty)
                            .addComponent(jLabel4qty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5price)
                            .addComponent(jTextFieldprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(0, 51, 51));
        jPanel9.setPreferredSize(new java.awt.Dimension(1110, 155));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_inventoryManagement/logo1.jpg"))); // NOI18N
        jLabel15.setText("jLabel12");

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 24)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Wide Latin", 0, 55)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kottawatta River Bank Resort");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel11))
                            .addComponent(jLabel15)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mealspanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1874, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mealspanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonInvActionPerformed
        // TODO add your handling code here:
        new Inventory_Dash().setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jToggleButtonInvActionPerformed

    private void jToggleButtonEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEmpActionPerformed
        // TODO add your handling code here:
        new EmpMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButtonEmpActionPerformed

    private void jToggleButtonFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonFinActionPerformed
        // TODO add your handling code here:
        new Finance_Mangemant().setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jToggleButtonFinActionPerformed

    private void jToggleButtonSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSupActionPerformed
        // TODO add your handling code here:
         new Supplier_Dashboard().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButtonSupActionPerformed

    private void jButton4refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4refreshActionPerformed

        jTable1.setModel(new DefaultTableModel(null, new Object[]{"item_Id", "item_Name", "qty", "price","total","billAmount"}));
        fooditems.fillFOODITEMSJTable(jTable1);
    }//GEN-LAST:event_jButton4refreshActionPerformed

    private void jButton1additemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1additemActionPerformed
        
        String itemName = (String) jComboBox1.getSelectedItem();
        Integer quantity = Integer.parseInt(jTextFieldqty.getText());
        Double price = Double.parseDouble(jTextFieldprice.getText());
        Double total = quantity*price;
        Double billAmount=0.0;
        for(int i=0;i<jTable1.getRowCount();i++){
        billAmount = total + Double.parseDouble(jTable1.getValueAt(i, 5).toString());
                
        }
        
        //if(itemName.isEmpty()){
        //    JOptionPane.showMessageDialog(rootPane, "Required Fileds", "Fill Empty Fileds", JOptionPane.WARNING_MESSAGE);
        //}
        
        //else{
           
      
        if (fooditems.addfooditems(itemName, quantity, price, total,billAmount)) {
            JOptionPane.showMessageDialog(rootPane, "New Food Item Add Successfully", "Add Food Item", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Food Item not Add", "Add not FoodItem", JOptionPane.INFORMATION_MESSAGE);
        }
        
        jTextFielditemId.setText("");
        jTextFieldqty.setText("");
        jTextFieldprice.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1additemActionPerformed

    private void jButton3deleteitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3deleteitemActionPerformed

        int itemId = Integer.valueOf(jTextFielditemId.getText());
        
        //delete the selected Order
        if (fooditems.deletefooditems(itemId)) {
            JOptionPane.showMessageDialog(rootPane, "Fooditems details deleted successfully", "Delete Item", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Fooditems Details Not deleted", "Delete Item Error", JOptionPane.ERROR_MESSAGE);
        }
        jTextFielditemId.setText("");
    }//GEN-LAST:event_jButton3deleteitemActionPerformed

    private void jTextFieldqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldqtyActionPerformed

    private void jToggleButtonRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRestActionPerformed

        new ResManagement().setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jToggleButtonRestActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MessageFormat header = new MessageFormat("Monthly Report");
               MessageFormat footer = new MessageFormat("Page[0,number,integer]");
               
               try{
               jTable1.print(JTable.PrintMode.NORMAL,header,footer);
               
               }catch(java.awt.print.PrinterException e){
               
               System.err.format("Cannot print %s%n",e.getMessage());
               }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void addmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmenuActionPerformed
        
        String itemName = (String) menuitem.getText();
        Double price = Double.parseDouble(menuprice.getText());
        
      
        if(itemName.isEmpty()){
           JOptionPane.showMessageDialog(rootPane, "Required Fileds", "Fill Empty Fileds", JOptionPane.WARNING_MESSAGE);
       }
        
        else{
           
      
        if (menuitems.addmenuitems(itemName,price)) {
            JOptionPane.showMessageDialog(rootPane, "New Food Item Add Successfully", "Add Food Item", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Food Item not Add", "Add not FoodItem", JOptionPane.INFORMATION_MESSAGE);
       }
        menuitem.setText("");
        menuprice.setText("");
         
        //String itemName= getString("item_Name");
       
        
        

        // TODO add your handling code here:
        
        
        }
    }//GEN-LAST:event_addmenuActionPerformed

    private void deletemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletemenuActionPerformed
        
          int itemId = Integer.valueOf(menuid.getText());
         // jComboBox1.removeItem(itemName);
        
        //delete the selected Order
        if (menuitems.deletemenuitems(itemId)) {
            JOptionPane.showMessageDialog(rootPane, "Menuitem details deleted successfully", "Delete Item", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Menuitem Details Not deleted", "Delete Item Error", JOptionPane.ERROR_MESSAGE);
        }
        menuid.setText("");
        menuitem.setText("");
        menuprice.setText("");
    }//GEN-LAST:event_deletemenuActionPerformed

    private void menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuitemActionPerformed

    private void menupriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menupriceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        jTable2.setModel(new DefaultTableModel(null, new Object[]{"item_Id","item_Name","price"}));
        menuitems.fillMENUITEMSJTable(jTable2);
        menuitems.jcomboupdate();
     // TODO add your handling code here:
      
         
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void updatemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatemenuActionPerformed
        
       int itemId ;
        String itemName = menuitem.getText();
        Double price =Double.parseDouble(menuprice.getText());
        try {
            itemId = Integer.valueOf(menuid.getText());
            
            boolean res = menuitems.updatemenuitems(itemId, itemName, price);

            if (res) {
                JOptionPane.showMessageDialog(rootPane, "Update Menuitem  Successfully", "Update menuitems", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, " Menuitem not Update", "Update not menuitems", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(rootPane, ne.getMessage() + "Enter the Item Id", "Item Id Error", JOptionPane.ERROR_MESSAGE);
        }
        menuid.setText("");
        menuitem.setText("");
        menuprice.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_updatemenuActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int selectedRow = jTable2.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        menuid.setText(model.getValueAt(selectedRow, 0).toString());
        menuitem.setText(model.getValueAt(selectedRow, 1).toString());
        menuprice.setText(model.getValueAt(selectedRow, 2).toString());
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        jTextFielditemId.setText(model.getValueAt(selectedRow, 0).toString());
        jComboBox1.setSelectedItem(model.getValueAt(selectedRow, 1).toString());
        jTextFieldqty.setText(model.getValueAt(selectedRow, 2).toString());
        jTextFieldprice.setText(model.getValueAt(selectedRow, 3).toString());
        

// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextFieldpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldpriceActionPerformed

    private void jToggleButtoncusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtoncusActionPerformed
        // TODO add your handling code here:
        new CusManagement().setVisible(true);
        this.setVisible(false);   
    }//GEN-LAST:event_jToggleButtoncusActionPerformed

    private void jToggleButtonBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBillActionPerformed
        // TODO add your handling code here:
        new RoomMenu().setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jToggleButtonBillActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 new Login().setVisible(true);
        this.setVisible(false);              // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmenu;
    private javax.swing.JButton deletemenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1additem;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton3deleteitem;
    private javax.swing.JButton jButton4refresh;
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2itemid;
    private javax.swing.JLabel jLabel3itemname;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4qty;
    private javax.swing.JLabel jLabel5price;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFielditemId;
    private javax.swing.JTextField jTextFieldprice;
    private javax.swing.JTextField jTextFieldqty;
    private javax.swing.JToggleButton jToggleButtonBill;
    private javax.swing.JToggleButton jToggleButtonEmp;
    private javax.swing.JToggleButton jToggleButtonFin;
    private javax.swing.JToggleButton jToggleButtonInv;
    private javax.swing.JToggleButton jToggleButtonRest;
    private javax.swing.JToggleButton jToggleButtonSup;
    private javax.swing.JToggleButton jToggleButtoncus;
    private javax.swing.JPanel mealspanel1;
    private javax.swing.JTextField menuid;
    private javax.swing.JTextField menuitem;
    private javax.swing.JTextField menuprice;
    private javax.swing.JButton updatemenu;
    // End of variables declaration//GEN-END:variables

   
}
