/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inteface_employeeManagement;

import DB.Connectivity;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import java_emp.EmployeeDetails;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Add_Employee extends javax.swing.JFrame {

    /**
     * Creates new form Add_Employee
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    EmployeeDetails empDetails = new EmployeeDetails();

    public Add_Employee() {
        initComponents();

        con = Connectivity.createConnection();

        empDetails.fillEmployeeDetailsJTable(jTableEmpDetails);
        empDetails.fillEmployeeBlackListDetailsJTable(jTableEmpBlaickList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonCustomerManagement = new javax.swing.JButton();
        jButtonBillManagement = new javax.swing.JButton();
        jButtonRsManagement = new javax.swing.JButton();
        jButtonInManagement = new javax.swing.JButton();
        jButtonEmpManagement = new javax.swing.JButton();
        jButtonFinManagement = new javax.swing.JButton();
        jButtonSupMAnagement = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmpNic = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmpAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldEmpEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEmpContactNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxEmpJobType = new javax.swing.JComboBox<>();
        jButtonEmpAdd = new javax.swing.JButton();
        jButtonEmpUpdate = new javax.swing.JButton();
        jButtonEmpDelete = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpDetails = new javax.swing.JTable();
        jButtonCuEmpDetailRefresh = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEmpBlaickList = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldEmpName = new javax.swing.JTextField();
        jTextFieldEmpID = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("              Employee Management");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(495, 495, 495)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jButtonCustomerManagement.setBackground(new java.awt.Color(255, 255, 204));
        jButtonCustomerManagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCustomerManagement.setText("Customer Management ");

        jButtonBillManagement.setBackground(new java.awt.Color(255, 255, 204));
        jButtonBillManagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBillManagement.setText("Bill & Booking Management");
        jButtonBillManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillManagementActionPerformed(evt);
            }
        });

        jButtonRsManagement.setBackground(new java.awt.Color(255, 255, 204));
        jButtonRsManagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonRsManagement.setText("Restuarant Management");

        jButtonInManagement.setBackground(new java.awt.Color(255, 255, 204));
        jButtonInManagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonInManagement.setText("Inventory Management");

        jButtonEmpManagement.setBackground(new java.awt.Color(255, 255, 204));
        jButtonEmpManagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonEmpManagement.setText("Employee Management");
        jButtonEmpManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpManagementActionPerformed(evt);
            }
        });

        jButtonFinManagement.setBackground(new java.awt.Color(255, 255, 204));
        jButtonFinManagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonFinManagement.setText("Finance Management");

        jButtonSupMAnagement.setBackground(new java.awt.Color(255, 255, 204));
        jButtonSupMAnagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSupMAnagement.setText("Supplier Management");
        jButtonSupMAnagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupMAnagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSupMAnagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFinManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEmpManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonInManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRsManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCustomerManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBillManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButtonCustomerManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButtonBillManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButtonRsManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButtonInManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButtonEmpManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButtonFinManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButtonSupMAnagement, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Employee Details");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Employee ID: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NIC:");

        jTextFieldEmpNic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Address:");

        jTextFieldEmpAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Email:");

        jTextFieldEmpEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Contact NO:");

        jTextFieldEmpContactNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Job Type:");

        jComboBoxEmpJobType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxEmpJobType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Manager", "Waiter", "Room Boy", "Reciptionist", " " }));

        jButtonEmpAdd.setBackground(new java.awt.Color(0, 51, 153));
        jButtonEmpAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonEmpAdd.setText("ADD");
        jButtonEmpAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpAddActionPerformed(evt);
            }
        });

        jButtonEmpUpdate.setBackground(new java.awt.Color(0, 204, 0));
        jButtonEmpUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonEmpUpdate.setText("UPDATE");
        jButtonEmpUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpUpdateActionPerformed(evt);
            }
        });

        jButtonEmpDelete.setBackground(new java.awt.Color(255, 0, 0));
        jButtonEmpDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonEmpDelete.setText("DELETE");
        jButtonEmpDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpDeleteActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));

        jTableEmpDetails.setBackground(new java.awt.Color(102, 102, 102));
        jTableEmpDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp_Id", "Name", "NIC", "Address", "Email", "Contact_No", "Job_Type"
            }
        )
        //make empployee table cell not editable
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTableEmpDetails.setGridColor(new java.awt.Color(255, 102, 255));
    jTableEmpDetails.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTableEmpDetailsMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTableEmpDetails);

    jButtonCuEmpDetailRefresh.setBackground(new java.awt.Color(0, 0, 0));
    jButtonCuEmpDetailRefresh.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jButtonCuEmpDetailRefresh.setForeground(new java.awt.Color(255, 255, 255));
    jButtonCuEmpDetailRefresh.setText("REFRESH");
    jButtonCuEmpDetailRefresh.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonCuEmpDetailRefreshActionPerformed(evt);
        }
    });

    jTableEmpBlaickList.setBackground(new java.awt.Color(102, 102, 102));
    jTableEmpBlaickList.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Blacklist_Id", "Emp_Id", "Name", "NIC", "Address", "Email", "Contact_No", "Job_Type"
        }
    ));
    jScrollPane3.setViewportView(jTableEmpBlaickList);

    jPanel6.setBackground(new java.awt.Color(255, 255, 255));

    jLabel11.setBackground(new java.awt.Color(0, 0, 0));
    jLabel11.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
    jLabel11.setText("Current Employee Details");

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel11)
            .addContainerGap(23, Short.MAX_VALUE))
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addComponent(jLabel11)
            .addGap(0, 15, Short.MAX_VALUE))
    );

    jPanel7.setBackground(new java.awt.Color(255, 255, 255));

    jLabel10.setBackground(new java.awt.Color(255, 102, 255));
    jLabel10.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
    jLabel10.setText("BackList Employee Details");

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel10)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel7Layout.setVerticalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
            .addContainerGap())
    );

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE))))
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButtonCuEmpDetailRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(151, 151, 151)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 0, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(7, 7, 7)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(32, 32, 32)
            .addComponent(jButtonCuEmpDetailRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(73, 73, 73))
    );

    jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel12.setText("Employee Name: ");

    jTextFieldEmpName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

    jTextFieldEmpID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

    jPanel9.setBackground(new java.awt.Color(0, 51, 51));
    jPanel9.setPreferredSize(new java.awt.Dimension(1110, 155));

    jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_inventoryManagement/logo1.jpg"))); // NOI18N
    jLabel14.setText("jLabel12");

    jButton18.setBackground(new java.awt.Color(0, 204, 0));
    jButton18.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 24)); // NOI18N
    jButton18.setText("LOGOUT");
    jButton18.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton18ActionPerformed(evt);
        }
    });

    jLabel15.setFont(new java.awt.Font("Wide Latin", 0, 55)); // NOI18N
    jLabel15.setForeground(new java.awt.Color(255, 255, 255));
    jLabel15.setText("Kottawatta River Bank Resort");

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(74, 74, 74)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 1453, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(63, 63, 63))
    );
    jPanel9Layout.setVerticalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addComponent(jLabel13)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(jLabel15))
                        .addComponent(jLabel14)))
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(8, 8, 8)))
            .addContainerGap(51, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonEmpAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65)
                            .addComponent(jButtonEmpUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(jButtonEmpDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(122, 122, 122)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldEmpNic, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldEmpAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldEmpEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldEmpContactNo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxEmpJobType, javax.swing.GroupLayout.Alignment.LEADING, 0, 211, Short.MAX_VALUE)
                                .addComponent(jTextFieldEmpName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldEmpID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGap(135, 135, 135))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(192, 192, 192)))
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 1898, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(jTextFieldEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(jTextFieldEmpNic, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(jTextFieldEmpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(jTextFieldEmpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(jTextFieldEmpContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(jComboBoxEmpJobType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(68, 68, 68)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonEmpDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEmpUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEmpAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(66, 66, 66))
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEmpUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpUpdateActionPerformed
        // TODO add your handling code here:

        int empId = 0;
        String empName = jTextFieldEmpName.getText();
        String nic = jTextFieldEmpNic.getText();
        String address = jTextFieldEmpAddress.getText();
        String email = jTextFieldEmpEmail.getText();
        //String category = String.valueOf(jComboBoxCategory.getSelectedItem().toString());
        String contactNo = jTextFieldEmpContactNo.getText();
        String jbType = String.valueOf(jComboBoxEmpJobType.getSelectedItem().toString());
        
        if(empName.isEmpty() || nic.isEmpty() || address.isEmpty() || email.isEmpty() || contactNo.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Required Fields ", "Fill Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else if(!(Pattern.matches("^[0-9]{10}+$", jTextFieldEmpContactNo.getText()))){
                    
            JOptionPane.showMessageDialog(rootPane, "Please enter a valid phone number", "Phone number Error", JOptionPane.ERROR_MESSAGE); 
            jTextFieldEmpContactNo.setText("");
        }
        else if(!(email.matches("^[A-Za-z0-9_.]+[@][A-Za-z.]+$"))){
            JOptionPane.showMessageDialog(rootPane, "Please enter a valid Email", "Email Error", JOptionPane.ERROR_MESSAGE);
            jTextFieldEmpEmail.setText("");
        }
        else if(!(nic.matches("^[0-9]{9}[vVxX]+$"))){
            JOptionPane.showMessageDialog(rootPane, "Invalid NIC number", "NIC Error", JOptionPane.ERROR_MESSAGE);
            jTextFieldEmpNic.setText("");
        }
        else{
            try {
            empId = Integer.valueOf(jTextFieldEmpID.getText());

            if (empDetails.updateEmployer(empId, empName, nic, address, email, contactNo, jbType)) {
                JOptionPane.showMessageDialog(rootPane, "Update Employer  Successfully", "Update Employer", JOptionPane.INFORMATION_MESSAGE);
                
                jTextFieldEmpID.setText("");
                jTextFieldEmpName.setText("");
                jTextFieldEmpNic.setText("");
                jTextFieldEmpAddress.setText("");
                jTextFieldEmpEmail.setText("");
                jTextFieldEmpContactNo.setText("");
                jComboBoxEmpJobType.setSelectedItem(" ");
                
            } else {
                JOptionPane.showMessageDialog(rootPane, " Employer not Update", "Update not Employer", JOptionPane.INFORMATION_MESSAGE);
            }
            } catch (NumberFormatException ne) {
                JOptionPane.showMessageDialog(rootPane, ne.getMessage() + "Enter the Employer Id", "Employee Id Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        

    }//GEN-LAST:event_jButtonEmpUpdateActionPerformed

    private void jButtonBillManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillManagementActionPerformed

    private void jButtonEmpAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpAddActionPerformed
        // TODO add your handling code here:
        String empName = jTextFieldEmpName.getText();
        String nic = jTextFieldEmpNic.getText();
        String address = jTextFieldEmpAddress.getText();
        String email = jTextFieldEmpEmail.getText();
        String contactNo = jTextFieldEmpContactNo.getText();
        String jbType = String.valueOf(jComboBoxEmpJobType.getSelectedItem().toString());

        if(empName.isEmpty() || nic.isEmpty() || address.isEmpty() || email.isEmpty() || contactNo.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Required Fields ", "Fill Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else if(!(Pattern.matches("^[0-9]{10}+$", jTextFieldEmpContactNo.getText()))){
                    
            JOptionPane.showMessageDialog(rootPane, "Please enter a valid phone number", "Phone number Error", JOptionPane.ERROR_MESSAGE); 
            jTextFieldEmpContactNo.setText("");
        }
        else if(!(email.matches("^[A-Za-z0-9_.]+[@][A-Za-z.]+$"))){
            JOptionPane.showMessageDialog(rootPane, "Please enter a valid Email", "Email Error", JOptionPane.ERROR_MESSAGE);
            jTextFieldEmpEmail.setText("");
        }
        else if(!(nic.matches("^[0-9]{9}[vVxX]+$"))){
            JOptionPane.showMessageDialog(rootPane, "Invalid NIC number", "NIC Error", JOptionPane.ERROR_MESSAGE);
            jTextFieldEmpNic.setText("");
        }
        else{
            if (empDetails.addEmployer(empName, nic, address, email, contactNo, jbType)) {
            JOptionPane.showMessageDialog(rootPane, "New Employer Add Successfully", "Add Employer", JOptionPane.INFORMATION_MESSAGE);
            
            jTextFieldEmpName.setText("");
            jTextFieldEmpNic.setText("");
            jTextFieldEmpAddress.setText("");
            jTextFieldEmpEmail.setText("");
            jTextFieldEmpContactNo.setText("");
            jComboBoxEmpJobType.setSelectedItem(" ");
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Employer not Add", "Add not Employer", JOptionPane.INFORMATION_MESSAGE);
        }
        }
        

        
    }//GEN-LAST:event_jButtonEmpAddActionPerformed

    private void jTableEmpDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpDetailsMouseClicked
        // TODO add your handling code here:
        // display the selected row data in the jTextfields
        //get the jTableEmployeeDetails model
        DefaultTableModel model = (DefaultTableModel) jTableEmpDetails.getModel();

        //get the selected row index
        int rIndex = jTableEmpDetails.getSelectedRow();
        
        jTableEmpDetails.setSelectionBackground(Color.WHITE);
        jTableEmpDetails.setSelectionForeground(Color.BLACK);

        //display data
        String jbType = jTableEmpDetails.getValueAt(rIndex, 6).toString();

        jTextFieldEmpID.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldEmpName.setText(model.getValueAt(rIndex, 1).toString());
        jTextFieldEmpNic.setText(model.getValueAt(rIndex, 2).toString());
        jTextFieldEmpAddress.setText(model.getValueAt(rIndex, 3).toString());
        jTextFieldEmpEmail.setText(model.getValueAt(rIndex, 4).toString());
        jTextFieldEmpContactNo.setText(model.getValueAt(rIndex, 5).toString());
        jComboBoxEmpJobType.setSelectedItem(jbType);
    }//GEN-LAST:event_jTableEmpDetailsMouseClicked

    private void jButtonCuEmpDetailRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuEmpDetailRefreshActionPerformed
        // TODO add your handling code here:

        //clear the JTableEmployeeDetails
        jTableEmpDetails.setModel(new DefaultTableModel(null, new Object[]{"Emp_Id", "Name", "NIC", "Address", "Email", "Contact_No", "Job_Type"}));

        //populate the JTableEmployeeDetails
        empDetails.fillEmployeeDetailsJTable(jTableEmpDetails);
        
         //clear the JTableEmployeeDetails
        jTableEmpBlaickList.setModel(new DefaultTableModel(null, new Object[]{"Blacklist_Id", "Emp_Id", "Name", "NIC", "Address", "Email", "Contact_No", "Job_Type"}));

        //populate the JTableEmployeeDetails
        empDetails.fillEmployeeBlackListDetailsJTable(jTableEmpBlaickList);
    }//GEN-LAST:event_jButtonCuEmpDetailRefreshActionPerformed

    private void jButtonEmpDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpDeleteActionPerformed
        // TODO add your handling code here:
        int empId = Integer.valueOf(jTextFieldEmpID.getText());
        
        String empName = jTextFieldEmpName.getText();
        String nic = jTextFieldEmpNic.getText();
        String address = jTextFieldEmpAddress.getText();
        String email = jTextFieldEmpEmail.getText();
        String contactNo = jTextFieldEmpContactNo.getText();
        String jbType = String.valueOf(jComboBoxEmpJobType.getSelectedItem().toString());

        //delete the selected Order
        if (empDetails.deleteEmployer(empId)) {
            JOptionPane.showMessageDialog(rootPane, "Employee details deleted successfully", "Delete Employee", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldEmpID.setText("");
            jTextFieldEmpName.setText("");
            jTextFieldEmpNic.setText("");
            jTextFieldEmpAddress.setText("");
            jTextFieldEmpEmail.setText("");
            jTextFieldEmpContactNo.setText("");
            jComboBoxEmpJobType.setSelectedItem(" ");

        } else {
            JOptionPane.showMessageDialog(rootPane, "Employee Details Not deleted", "Delete Employee Error", JOptionPane.ERROR_MESSAGE);
        }
           
        if(empDetails.blackListEmployer(empId, empName, nic, address, email, contactNo, jbType)){
            //JOptionPane.showMessageDialog(rootPane, "Employee details deleted successfully", "Delete Employee", JOptionPane.INFORMATION_MESSAGE);
        }else {
            JOptionPane.showMessageDialog(rootPane, "Employee Details Not deleted", "Delete Employee Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonEmpDeleteActionPerformed

    private void jButtonSupMAnagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupMAnagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSupMAnagementActionPerformed

    private void jButtonEmpManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpManagementActionPerformed
        // TODO add your handling code here:
        EmpMenu empMenu = new EmpMenu();
        empMenu.setVisible(true);
        empMenu.setLocationRelativeTo(null);
        empMenu.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jButtonEmpManagementActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButtonBillManagement;
    private javax.swing.JButton jButtonCuEmpDetailRefresh;
    private javax.swing.JButton jButtonCustomerManagement;
    private javax.swing.JButton jButtonEmpAdd;
    private javax.swing.JButton jButtonEmpDelete;
    private javax.swing.JButton jButtonEmpManagement;
    private javax.swing.JButton jButtonEmpUpdate;
    private javax.swing.JButton jButtonFinManagement;
    private javax.swing.JButton jButtonInManagement;
    private javax.swing.JButton jButtonRsManagement;
    private javax.swing.JButton jButtonSupMAnagement;
    private javax.swing.JComboBox<String> jComboBoxEmpJobType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableEmpBlaickList;
    private javax.swing.JTable jTableEmpDetails;
    private javax.swing.JTextField jTextFieldEmpAddress;
    private javax.swing.JTextField jTextFieldEmpContactNo;
    private javax.swing.JTextField jTextFieldEmpEmail;
    private javax.swing.JLabel jTextFieldEmpID;
    private javax.swing.JTextField jTextFieldEmpName;
    private javax.swing.JTextField jTextFieldEmpNic;
    // End of variables declaration//GEN-END:variables
}
