/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inteface_employeeManagement;


import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_emp.EmpAttendanceDetails;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class EmpAttendance extends javax.swing.JFrame {

    /**
     * Creates new form EmpAttendance
     */
    
    
    EmpAttendanceDetails empAttdetails = new EmpAttendanceDetails();
    
    public EmpAttendance() {
        initComponents();
        
        empAttdetails.fillEmployeeAttendanceJTable(jTableEmpAttendance);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButtonCustomerManagement = new javax.swing.JButton();
        jButtonBillManagement = new javax.swing.JButton();
        jButtonRsManagement = new javax.swing.JButton();
        jButtonInManagement = new javax.swing.JButton();
        jButtonEmpManagement = new javax.swing.JButton();
        jButtonFinManagement = new javax.swing.JButton();
        jButtonSupMAnagement = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmpID = new javax.swing.JTextField();
        attAddBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        attUpdateBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmpAttendance = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldOTHours = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooserAttDate = new com.toedter.calendar.JDateChooser();
        jTextFieldAttID = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1919, 1079));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jButtonCustomerManagement.setBackground(new java.awt.Color(255, 255, 153));
        jButtonCustomerManagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCustomerManagement.setText("Customer Management ");

        jButtonBillManagement.setBackground(new java.awt.Color(255, 255, 153));
        jButtonBillManagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBillManagement.setText("Bill & Booking Management");
        jButtonBillManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillManagementActionPerformed(evt);
            }
        });

        jButtonRsManagement.setBackground(new java.awt.Color(255, 255, 153));
        jButtonRsManagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonRsManagement.setText("Restuarant Management");

        jButtonInManagement.setBackground(new java.awt.Color(255, 255, 153));
        jButtonInManagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonInManagement.setText("Inventory Management");

        jButtonEmpManagement.setBackground(new java.awt.Color(255, 255, 153));
        jButtonEmpManagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonEmpManagement.setText("Employee Management");
        jButtonEmpManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpManagementActionPerformed(evt);
            }
        });

        jButtonFinManagement.setBackground(new java.awt.Color(255, 255, 153));
        jButtonFinManagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonFinManagement.setText("Finance Management");

        jButtonSupMAnagement.setBackground(new java.awt.Color(255, 255, 153));
        jButtonSupMAnagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSupMAnagement.setText("Supplier Management");
        jButtonSupMAnagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupMAnagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSupMAnagement, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonFinManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEmpManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonInManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRsManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBillManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCustomerManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButtonCustomerManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButtonBillManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButtonRsManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonInManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButtonEmpManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButtonFinManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButtonSupMAnagement, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Employee ID: ");

        jTextFieldEmpID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpIDActionPerformed(evt);
            }
        });

        attAddBtn.setBackground(new java.awt.Color(0, 51, 153));
        attAddBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        attAddBtn.setText("ADD");
        attAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attAddBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Date:");

        attUpdateBtn.setBackground(new java.awt.Color(0, 204, 0));
        attUpdateBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        attUpdateBtn.setText("UPDATE");
        attUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attUpdateBtnActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("REFRESH");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTableEmpAttendance.setBackground(new java.awt.Color(102, 102, 102));
        jTableEmpAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Attendance_ID", "Emp_ID", "Date", "Month", "OT_Hours"
            }
        )
        //make empployee table cell not editable
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTableEmpAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTableEmpAttendanceMouseClicked(evt);
        }
    });
    jScrollPane2.setViewportView(jTableEmpAttendance);

    jPanel6.setBackground(new java.awt.Color(255, 255, 255));
    jPanel6.setForeground(new java.awt.Color(255, 255, 255));

    jLabel11.setBackground(new java.awt.Color(255, 102, 255));
    jLabel11.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
    jLabel11.setText("Current Employee Attendance Details");

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel11)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 8, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(33, 33, 33))
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(36, 36, 36)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTextFieldOTHours.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jTextFieldOTHours.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldOTHoursActionPerformed(evt);
        }
    });

    jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel7.setText("OT Hours:");

    jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(0, 153, 153));
    jLabel2.setText("Employee Attendance Details");

    jPanel3.setBackground(new java.awt.Color(0, 51, 51));

    jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("                     Employee Management");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(495, 495, 495)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
            .addContainerGap())
    );

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel3.setText("Attendance ID:");

    jDateChooserAttDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

    jTextFieldAttID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

    jPanel9.setBackground(new java.awt.Color(0, 51, 51));
    jPanel9.setPreferredSize(new java.awt.Dimension(1110, 155));

    jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_inventoryManagement/logo1.jpg"))); // NOI18N
    jLabel14.setText("jLabel12");

    jButton18.setBackground(new java.awt.Color(0, 204, 0));
    jButton18.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 24)); // NOI18N
    jButton18.setText("LOGOUT");
    jButton18.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton18ActionPerformed(evt);
        }
    });

    jLabel15.setFont(new java.awt.Font("Wide Latin", 0, 55)); // NOI18N
    jLabel15.setForeground(new java.awt.Color(255, 255, 255));
    jLabel15.setText("Kottawatta River Bank Resort");

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(74, 74, 74)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 1453, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(63, 63, 63))
    );
    jPanel9Layout.setVerticalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addComponent(jLabel13)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(jLabel15))
                        .addComponent(jLabel14)))
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(8, 8, 8)))
            .addContainerGap(51, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(87, 87, 87)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)
                    .addComponent(jTextFieldAttID, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)
                    .addComponent(jTextFieldEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(attAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(58, 58, 58)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOTHours, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserAttDate, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(attUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 1919, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(25, 25, 25)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(42, 42, 42)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldAttID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(63, 63, 63)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(67, 67, 67)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDateChooserAttDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(76, 76, 76)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldOTHours, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(109, 109, 109)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(attAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(attUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        //clear the JTableEmployeeDetails
        jTableEmpAttendance.setModel(new DefaultTableModel(null, new Object[]{"Attendance_Id", "Emp_Id", "Date", "Month", "OtHours"}));

        //populate the JTableEmployeeDetails
        empAttdetails.fillEmployeeAttendanceJTable(jTableEmpAttendance);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void attUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attUpdateBtnActionPerformed
        // TODO add your handling code here:
        
        int attId = 0;
        int empId = Integer.valueOf(jTextFieldEmpID.getText());
        
        java.util.Date date = jDateChooserAttDate.getDate();
        SimpleDateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date1 = oDateFormat.format(date); 
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
	Date dateCheck = new Date();
	String checkDate = (formatter.format(dateCheck));
        
       
        Calendar mCalendar = Calendar.getInstance();    
        String month = mCalendar.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.getDefault());
        
        int otHours = Integer.valueOf(jTextFieldOTHours.getText());
        
       try {
            attId = Integer.valueOf(jTextFieldAttID.getText());
            
            if(checkDate.equals(date1)){
                if (empAttdetails.updateEmployerAttendance(attId, empId, date1, month, otHours)) {
                JOptionPane.showMessageDialog(rootPane, "Update Employer Attendance Successfully", "Update Attendance Employer details", JOptionPane.INFORMATION_MESSAGE);
                
                jTextFieldAttID.setText("");
                jTextFieldEmpID.setText("");
                jDateChooserAttDate.setDate(null);
                jTextFieldOTHours.setText("");
        
            } else {
                JOptionPane.showMessageDialog(rootPane, " Employer Attendance not Update", "Update not Employer Attendance", JOptionPane.INFORMATION_MESSAGE);
            }
           }
            else{
                JOptionPane.showMessageDialog(rootPane, "Enter the current Date", "Date Error", JOptionPane.ERROR_MESSAGE);
                jDateChooserAttDate.setDate(null);
            }

            
        } catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(rootPane, ne.getMessage() + "Enter the Employer Attendance Id", "Attendance Id Error", JOptionPane.ERROR_MESSAGE);
        }
       
        
    }//GEN-LAST:event_attUpdateBtnActionPerformed

    private void jButtonBillManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillManagementActionPerformed

    private void attAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attAddBtnActionPerformed
        // TODO add your handling code here:
        
        String empId = jTextFieldEmpID.getText();
        //String date =   jDateChooserAttDate.getDateFormatString();
        java.util.Date date = jDateChooserAttDate.getDate();
        SimpleDateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date1 = oDateFormat.format(date); 
       
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
	Date dateCheck = new Date();
	String checkDate = (formatter.format(dateCheck));
         
        String otHours = jTextFieldOTHours.getText();
        
        Calendar mCalendar = Calendar.getInstance();    
        String month = mCalendar.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.getDefault());
        
        if(empId.isEmpty() || otHours.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Required Fields ", "Fill Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else if(checkDate.equals(date1)){
            //java.sql.Date date = new java.sql.Date(jDateChooserAttDate.getDate().getTime());
        if (empAttdetails.addEmployerAttendance(empId, date1,month, otHours)) {
            JOptionPane.showMessageDialog(rootPane, "New Employer Attendance Add Successfully", "Add Employer Attendace", JOptionPane.INFORMATION_MESSAGE);
            
            jTextFieldEmpID.setText("");
            jDateChooserAttDate.setDate(null);
            jTextFieldOTHours.setText("");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Employer Attendance not Add", "Add not Employer Attendance", JOptionPane.INFORMATION_MESSAGE);
        }
        }
        else{
           JOptionPane.showMessageDialog(rootPane, "Enter the current Date", "Date Error", JOptionPane.ERROR_MESSAGE);
           jDateChooserAttDate.setDate(null);
        }
        
        
        
    }//GEN-LAST:event_attAddBtnActionPerformed

    private void jTableEmpAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpAttendanceMouseClicked
        // TODO add your handling code here:
        
        //get the jTableEmployeeAttendanceDetails model
        DefaultTableModel model = (DefaultTableModel) jTableEmpAttendance.getModel();

        //get the selected row index
        int rIndex = jTableEmpAttendance.getSelectedRow();
        
        jTableEmpAttendance.setSelectionBackground(Color.WHITE);
        jTableEmpAttendance.setSelectionForeground(Color.BLACK);

        //display data
        Date date = null;
        try {
            date =   new SimpleDateFormat("yyyy-MM-dd").parse((String) jTableEmpAttendance.getValueAt(rIndex, 2));

        } catch (ParseException ex) {
            Logger.getLogger(EmpAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
        String month = jTableEmpAttendance.getValueAt(rIndex, 3).toString();
        
        jTextFieldAttID.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldEmpID.setText(model.getValueAt(rIndex, 1).toString());
        jDateChooserAttDate.setDate(date);
       // jComboBoxMonth.setSelectedItem(month);
        jTextFieldOTHours.setText(model.getValueAt(rIndex, 4).toString());
    }//GEN-LAST:event_jTableEmpAttendanceMouseClicked

    private void jTextFieldOTHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOTHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOTHoursActionPerformed

    private void jTextFieldEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpIDActionPerformed

    private void jButtonSupMAnagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupMAnagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSupMAnagementActionPerformed

    private void jButtonEmpManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpManagementActionPerformed
        // TODO add your handling code here:
        EmpMenu empMenu = new EmpMenu();
        empMenu.setVisible(true);
        empMenu.setLocationRelativeTo(null);
        empMenu.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jButtonEmpManagementActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attAddBtn;
    private javax.swing.JButton attUpdateBtn;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonBillManagement;
    private javax.swing.JButton jButtonCustomerManagement;
    private javax.swing.JButton jButtonEmpManagement;
    private javax.swing.JButton jButtonFinManagement;
    private javax.swing.JButton jButtonInManagement;
    private javax.swing.JButton jButtonRsManagement;
    private javax.swing.JButton jButtonSupMAnagement;
    private com.toedter.calendar.JDateChooser jDateChooserAttDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEmpAttendance;
    private javax.swing.JLabel jTextFieldAttID;
    private javax.swing.JTextField jTextFieldEmpID;
    private javax.swing.JTextField jTextFieldOTHours;
    // End of variables declaration//GEN-END:variables
}
