/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_inventoryManagement;

import DB.MY_CONNECTION;
import Interface.Login;
import Java_inventoryManagement.RoomInventoryDetails;
import Java_inventoryManagement.roominventory;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kasuni Piyumali
 */
public class RoomInventory extends javax.swing.JFrame {
roominventory room = new roominventory();
    /**
     * Creates new form RoomInventory
     */
    public RoomInventory() {
        initComponents();
        Room_Inventory();
         room.fillRoomInventoryProductDetailsJTable(jTableroom);
    }
    public class catregoryRoomItem{
        int id;
        String name;
        
        public catregoryRoomItem(int id, String name){
            this.id=id;
            this.name=name;
        }
        public String toString(){
            return name;
        }
    }
    
     private void Room_Inventory(){
        PreparedStatement ps;
        ResultSet rs;
        
        MY_CONNECTION my_connection = new MY_CONNECTION();
        String selectQuery = "SELECT * FROM `roominventory`";
        
        try {
            ps = my_connection.createConnection().prepareStatement(selectQuery);
            
            rs = ps.executeQuery();
          
            jComboBoxroom.removeAllItems();
            
            
            while(rs.next())
            {
              jComboBoxroom.addItem(new catregoryRoomItem(rs.getInt(1),rs.getString(2)));
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RoomInventoryDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButtonCustomerMangment = new javax.swing.JButton();
        jButtonCustomerMangment2 = new javax.swing.JButton();
        jButtonCustomerMangment3 = new javax.swing.JButton();
        jButtonCustomerMangment4 = new javax.swing.JButton();
        jButtonCustomerMangment5 = new javax.swing.JButton();
        jButtonCustomerMangment6 = new javax.swing.JButton();
        jButtonCustomerMangment7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxroom = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldqty = new javax.swing.JTextField();
        jButtonnewproduct = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonincrease = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableroom = new javax.swing.JTable();
        jButtonroom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtondecrease = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonprint = new javax.swing.JButton();
        show_validation_here = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));
        jPanel7.setPreferredSize(new java.awt.Dimension(1500, 96));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Room Inventory Management");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(445, 445, 445)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(21, 21, 21))
        );

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));

        jButtonCustomerMangment.setBackground(new java.awt.Color(255, 255, 204));
        jButtonCustomerMangment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCustomerMangment.setText("Customer Management");
        jButtonCustomerMangment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerMangmentActionPerformed(evt);
            }
        });

        jButtonCustomerMangment2.setBackground(new java.awt.Color(255, 255, 204));
        jButtonCustomerMangment2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCustomerMangment2.setText("Bill & Booking Management");
        jButtonCustomerMangment2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerMangment2ActionPerformed(evt);
            }
        });

        jButtonCustomerMangment3.setBackground(new java.awt.Color(255, 255, 204));
        jButtonCustomerMangment3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCustomerMangment3.setText("Resturant Management");
        jButtonCustomerMangment3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerMangment3ActionPerformed(evt);
            }
        });

        jButtonCustomerMangment4.setBackground(new java.awt.Color(255, 255, 204));
        jButtonCustomerMangment4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCustomerMangment4.setText("Inventory Management");
        jButtonCustomerMangment4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerMangment4ActionPerformed(evt);
            }
        });

        jButtonCustomerMangment5.setBackground(new java.awt.Color(255, 255, 204));
        jButtonCustomerMangment5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCustomerMangment5.setText("Employee Management");
        jButtonCustomerMangment5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerMangment5ActionPerformed(evt);
            }
        });

        jButtonCustomerMangment6.setBackground(new java.awt.Color(255, 255, 204));
        jButtonCustomerMangment6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCustomerMangment6.setText("Finance Management");
        jButtonCustomerMangment6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerMangment6ActionPerformed(evt);
            }
        });

        jButtonCustomerMangment7.setBackground(new java.awt.Color(255, 255, 204));
        jButtonCustomerMangment7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCustomerMangment7.setText("Supplier Management");
        jButtonCustomerMangment7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerMangment7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCustomerMangment, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCustomerMangment2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCustomerMangment3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCustomerMangment4, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCustomerMangment5, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCustomerMangment6, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCustomerMangment7, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButtonCustomerMangment, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtonCustomerMangment2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtonCustomerMangment3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtonCustomerMangment4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtonCustomerMangment5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtonCustomerMangment6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtonCustomerMangment7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Room Inventory Product Name");

        jComboBoxroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxroomActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Qty");

        jTextFieldqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldqtyActionPerformed(evt);
            }
        });
        jTextFieldqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldqtyKeyPressed(evt);
            }
        });

        jButtonnewproduct.setBackground(new java.awt.Color(51, 153, 255));
        jButtonnewproduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonnewproduct.setText("Add New Room Inventory Product ");
        jButtonnewproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnewproductActionPerformed(evt);
            }
        });

        jButtonincrease.setBackground(new java.awt.Color(0, 0, 0));
        jButtonincrease.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonincrease.setForeground(new java.awt.Color(255, 255, 255));
        jButtonincrease.setText("Add To Current Inventory");
        jButtonincrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonincreaseActionPerformed(evt);
            }
        });

        jTableroom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Inventory Product  Name", "Qty"
            }
        ));
        jScrollPane1.setViewportView(jTableroom);

        jButtonroom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonroom.setText("Refresh");
        jButtonroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonroomActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setText("Room Inventory Products Quantity ");

        jButtondecrease.setBackground(new java.awt.Color(0, 0, 0));
        jButtondecrease.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtondecrease.setForeground(new java.awt.Color(255, 255, 255));
        jButtondecrease.setText("Remove From Room");
        jButtondecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondecreaseActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Current Room Inventories Quantity Details");

        jButtonprint.setBackground(new java.awt.Color(255, 102, 102));
        jButtonprint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonprint.setForeground(new java.awt.Color(255, 255, 255));
        jButtonprint.setText("AVALIABLE ROOM INVENTORIES REPORT ");
        jButtonprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonprintActionPerformed(evt);
            }
        });

        show_validation_here.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxroom, 0, 204, Short.MAX_VALUE)
                            .addComponent(jTextFieldqty, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(show_validation_here, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonincrease)
                        .addGap(18, 18, 18)
                        .addComponent(jButtondecrease, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                    .addComponent(jButtonnewproduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(219, 219, 219)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addComponent(jButtonroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(462, 462, 462)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(jButtonprint, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonroom)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxroom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldqty, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(4, 4, 4)
                        .addComponent(show_validation_here, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButtonnewproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonincrease, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtondecrease, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButtonprint, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1965, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setPreferredSize(new java.awt.Dimension(1110, 155));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_inventoryManagement/logo1.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 24)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Wide Latin", 0, 55)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kottawatta River Bank Resort");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1965, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1965, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 new Login().setVisible(true);
        this.setVisible(false);                      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCustomerMangmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerMangmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCustomerMangmentActionPerformed

    private void jButtonCustomerMangment2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerMangment2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCustomerMangment2ActionPerformed

    private void jButtonCustomerMangment3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerMangment3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCustomerMangment3ActionPerformed

    private void jButtonCustomerMangment4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerMangment4ActionPerformed
        new Inventory_Dash().setVisible(true);
        this.setVisible(false);                // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCustomerMangment4ActionPerformed

    private void jButtonCustomerMangment5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerMangment5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCustomerMangment5ActionPerformed

    private void jButtonCustomerMangment6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerMangment6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCustomerMangment6ActionPerformed

    private void jButtonCustomerMangment7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerMangment7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCustomerMangment7ActionPerformed

    private void jTextFieldqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldqtyActionPerformed

    private void jButtonnewproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnewproductActionPerformed
        catregoryRoomItem citem=(catregoryRoomItem)jComboBoxroom.getSelectedItem();
        String qty = jTextFieldqty.getText();
        //String status = String.valueOf(jComboBoxstatus.getSelectedItem().toString());
        int Qty = Integer.parseInt(qty);

        if(citem.name.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Required Fileds", "Fill Empty Fileds", JOptionPane.WARNING_MESSAGE);
        }
        else{
            if (room.addproduct(citem.name, Qty)) {
                JOptionPane.showMessageDialog(rootPane, "New Room Inventory Product Add Successfully", "Add Room Inventory Product Qty", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Room Inventory Product not Add", "Add not Room Product Qty", JOptionPane.INFORMATION_MESSAGE);
            }

            jComboBoxroom.setSelectedIndex(-1);
            jTextFieldqty.setText("");
    }//GEN-LAST:event_jButtonnewproductActionPerformed
    }
    private void jButtonincreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonincreaseActionPerformed
        catregoryRoomItem citem=(catregoryRoomItem)jComboBoxroom.getSelectedItem();
        //String product=(String)jComboBox1.getSelectedItem();
        String qty=jTextFieldqty.getText();
        int Qty=Integer.parseInt(qty);
        //int Productid=Integer.parseInt(productid);

        try {

            if (room.updateproduct(citem.name, Qty)) {
                JOptionPane.showMessageDialog(rootPane, "Add Room Inventory Product qty Successfully", "Add Room Inventory Product qty", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, " Room Inventory prodcut qty not add before. Click Add New product Button and Try again", "Add not Room Inventory Product qty", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(rootPane, ne.getMessage() + "Enter the KItem Id", "Room inventory Id Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonincreaseActionPerformed

    private void jButtonroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonroomActionPerformed
        jTableroom.setModel(new DefaultTableModel(null, new Object[]{"Product Name", "Total Qty"}));

        //populate the JTableRoomInventoryDetails
        room.fillRoomInventoryProductDetailsJTable(jTableroom);
    }//GEN-LAST:event_jButtonroomActionPerformed

    private void jButtondecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondecreaseActionPerformed
        catregoryRoomItem citem=(catregoryRoomItem)jComboBoxroom.getSelectedItem();
        //String product=(String)jComboBox1.getSelectedItem();
        String qty=jTextFieldqty.getText();
        int Qty=Integer.parseInt(qty);
        //int Productid=Integer.parseInt(productid);

        try {

            if (room.decreaseproduct(citem.name, Qty)) {
                JOptionPane.showMessageDialog(rootPane, "Issued Product to Room  Successfully", "Issued Resturant", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Issued Product to Room failed", " not Issued Resturant", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(rootPane, ne.getMessage() + "Enter the KItem Id", "Room inventory Id Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtondecreaseActionPerformed

    private void jButtonprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonprintActionPerformed
  
        String path="";
        JFileChooser j=new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x=j.showSaveDialog(this);
        
        if(x==JFileChooser.APPROVE_OPTION){
            path=j.getSelectedFile().getPath();
        }
        
        Document doc = new Document();
        
         try {
             
             PdfWriter.getInstance(doc, new FileOutputStream(path+"Avaliable_Room_Inventory_Daily_Report.pdf"));
             
             doc.open();
            doc.add(new Paragraph("Avaliable Room Inventory Report"));
            
            
             PdfPTable tb1=new PdfPTable(2);
           
             tb1.addCell("Avaliable Room Item Name");
             tb1.addCell("Total Qunantity");
             
             
             for (int i=0 ; i <jTableroom.getRowCount();i++){
             
                   String ProductName = jTableroom.getValueAt(i,0).toString();
                   String Qty = jTableroom.getValueAt(i,1).toString();
                  
                   tb1.addCell(ProductName);
                   tb1.addCell(Qty);         
                       
             }
             doc.add(tb1);
         } catch (FileNotFoundException ex) {
             Logger.getLogger(Kitchen_Inventory.class.getName()).log(Level.SEVERE, null, ex);
         } catch (DocumentException ex) {
             Logger.getLogger(Kitchen_Inventory.class.getName()).log(Level.SEVERE, null, ex);
         }
        doc.close();
    }//GEN-LAST:event_jButtonprintActionPerformed

    private void jComboBoxroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxroomActionPerformed

    private void jTextFieldqtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldqtyKeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
        jTextFieldqty.setEditable(false);
        show_validation_here.setText("Please Enter Number only");
        
        }// TODO add your handling code here:
        else{
        jTextFieldqty.setEditable(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldqtyKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCustomerMangment;
    private javax.swing.JButton jButtonCustomerMangment2;
    private javax.swing.JButton jButtonCustomerMangment3;
    private javax.swing.JButton jButtonCustomerMangment4;
    private javax.swing.JButton jButtonCustomerMangment5;
    private javax.swing.JButton jButtonCustomerMangment6;
    private javax.swing.JButton jButtonCustomerMangment7;
    private javax.swing.JButton jButtondecrease;
    private javax.swing.JButton jButtonincrease;
    private javax.swing.JButton jButtonnewproduct;
    private javax.swing.JButton jButtonprint;
    private javax.swing.JButton jButtonroom;
    private javax.swing.JComboBox jComboBoxroom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableroom;
    private javax.swing.JTextField jTextFieldqty;
    private javax.swing.JLabel show_validation_here;
    // End of variables declaration//GEN-END:variables
}
